#!/bin/bash

set -Eeo pipefail

for command in "$@"
do
  echo "--- ${command} ---"
  case "${command}" in
    format)
        pipenv run format-import
        pipenv run format
        ;;
    check-format)
        pipenv run check-format
        ;;
    lint)
        pipenv run lint-flake8
        pipenv run lint-bandit
        ;;
    typecheck)
        pipenv run typecheck
        ;;
    check-deps)
        pipenv check
        ;;
    validate)
        ./tasks check-format typecheck lint test
        ;;
    clean)
        find ./tests -type f -name "*.pyc" -delete
        find ./tests -type d -name "__pycache__" -delete
        find ./src -type f -name "*.pyc" -delete
        find ./src -type d -name "__pycache__" -delete
        find ./src -type f -path "*.egg-info*" -delete
        find ./src -type d -path "*.egg-info" -delete
        rm -rf build/ dist/ .pytest_cache/
        ;;
    devenv)
        pipenv install
        ;;
    *)
        echo "Invalid command: '${command}'"
        exit 1
        ;;
  esac
done

set +e